# Generated by Django 4.2.30 on 2026-05-01 19:21

from django.db import migrations, models
import django.db.models.deletion
import reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('reconnaissance', 'Reconnaissance'), ('vulnerability_identification', 'Vulnerability Identification'), ('exploitation', 'Exploitation'), ('internal_reconnaissance', 'Internal Reconnaissance'), ('user_movement', 'User Movement'), ('privilege_escalation', 'Privilege Escalation'), ('flags', 'Flags'), ('notes', 'Notes')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('command', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['phase', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exploit_type', models.CharField(choices=[('Manual Technique', 'Manual Technique'), ('Custom Exploit', 'Custom Exploit'), ('GitHub Repository', 'GitHub Repository'), ('Searchsploit', 'Searchsploit'), ('Metasploit Module', 'Metasploit Module'), ('Public PoC', 'Public PoC'), ('Other', 'Other')], max_length=50)),
                ('cve', models.CharField(blank=True, max_length=50)),
                ('url', models.URLField(blank=True)),
                ('local_path', models.CharField(blank=True, max_length=255)),
                ('affected_service', models.CharField(blank=True, max_length=200)),
                ('affected_port', models.CharField(blank=True, max_length=50)),
                ('objective', models.CharField(choices=[('Initial Access', 'Initial Access'), ('Remote Code Execution', 'Remote Code Execution'), ('Credential Disclosure', 'Credential Disclosure'), ('User Pivot', 'User Pivot'), ('Privilege Escalation', 'Privilege Escalation'), ('Proof of Concept', 'Proof of Concept')], max_length=50)),
                ('command_used', models.TextField(blank=True)),
                ('output', models.TextField(blank=True)),
                ('result', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('HackTheBox', 'HackTheBox'), ('TryHackMe', 'TryHackMe'), ('VulnHub', 'VulnHub'), ('DockerLabs', 'DockerLabs'), ('Other', 'Other')], default='Other', max_length=20)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Insane', 'Insane'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('operating_system', models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('FreeBSD', 'FreeBSD'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='Unknown', max_length=10)),
                ('target_ip', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Paused', 'Paused')], default='In Progress', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('affected_service', models.CharField(blank=True, max_length=200)),
                ('affected_port', models.CharField(blank=True, max_length=50)),
                ('vulnerability_type', models.CharField(choices=[('SQL Injection', 'SQL Injection'), ('XSS', 'XSS'), ('LFI', 'LFI'), ('RFI', 'RFI'), ('SSRF', 'SSRF'), ('Command Injection', 'Command Injection'), ('File Upload', 'File Upload'), ('Path Traversal', 'Path Traversal'), ('Weak Credentials', 'Weak Credentials'), ('Exposed Backup', 'Exposed Backup'), ('Kernel Exploit', 'Kernel Exploit'), ('SUID Misconfiguration', 'SUID Misconfiguration'), ('Sudo Privileges', 'Sudo Privileges'), ('Misconfigured Service', 'Misconfigured Service'), ('Known CVE', 'Known CVE'), ('Other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('Info', 'Info'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Info', max_length=20)),
                ('cve', models.CharField(blank=True, max_length=50)),
                ('how_identified', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('impact', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='reports.machine')),
            ],
            options={
                'verbose_name_plural': 'Vulnerabilities',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, choices=[('reconnaissance', 'Reconnaissance'), ('vulnerability_identification', 'Vulnerability Identification'), ('exploitation', 'Exploitation'), ('internal_reconnaissance', 'Internal Reconnaissance'), ('user_movement', 'User Movement'), ('privilege_escalation', 'Privilege Escalation'), ('flags', 'Flags'), ('notes', 'Notes')], max_length=50)),
                ('image', models.ImageField(upload_to=reports.models.screenshot_upload_path)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='reports.evidence')),
                ('exploit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='reports.exploit')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='reports.machine')),
                ('vulnerability', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshots', to='reports.vulnerability')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_type', models.CharField(choices=[('user.txt', 'user.txt'), ('root.txt', 'root.txt'), ('local.txt', 'local.txt'), ('proof.txt', 'proof.txt'), ('other', 'other')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('obtained_as_user', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('censored', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='reports.machine')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='exploit',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exploits', to='reports.machine'),
        ),
        migrations.AddField(
            model_name='exploit',
            name='vulnerability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exploits', to='reports.vulnerability'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='reports.machine'),
        ),
    ]
