# Generated by Django 4.2.30 on 2026-05-01 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='report_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='es', max_length=2),
        ),
    ]
