# Generated by Django 4.2.30 on 2026-05-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_machine_report_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='client_name',
            field=models.CharField(blank=True, help_text='Company/client name (for Pentest/Bug Bounty reports)', max_length=200),
        ),
        migrations.AddField(
            model_name='machine',
            name='report_type',
            field=models.CharField(choices=[('ctf', 'CTF / HackTheBox / TryHackMe'), ('bug_bounty', 'Bug Bounty Report'), ('pentest', 'Penetration Test (Corporate)')], default='ctf', max_length=20),
        ),
        migrations.AddField(
            model_name='machine',
            name='scope',
            field=models.TextField(blank=True, help_text='Scope of the engagement (URLs, IP ranges, etc.)'),
        ),
    ]
