# Generated by Django 4.2.30 on 2026-05-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_machine_client_name_machine_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='phase',
            field=models.CharField(choices=[('reconnaissance', 'Reconnaissance'), ('vulnerability_identification', 'Vulnerability Identification'), ('exploitation', 'Exploitation'), ('internal_reconnaissance', 'Internal Reconnaissance'), ('user_movement', 'User Movement'), ('privilege_escalation', 'Privilege Escalation'), ('notes', 'Notes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='phase',
            field=models.CharField(blank=True, choices=[('reconnaissance', 'Reconnaissance'), ('vulnerability_identification', 'Vulnerability Identification'), ('exploitation', 'Exploitation'), ('internal_reconnaissance', 'Internal Reconnaissance'), ('user_movement', 'User Movement'), ('privilege_escalation', 'Privilege Escalation'), ('notes', 'Notes')], max_length=50),
        ),
    ]
