# Generated by Django 4.2.30 on 2026-05-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_evidence_phase_alter_screenshot_phase'),
    ]

    operations = [
        migrations.AddField(
            model_name='flag',
            name='found_commands',
            field=models.TextField(blank=True, help_text='Commands used to obtain this flag'),
        ),
        migrations.AddField(
            model_name='flag',
            name='phase',
            field=models.CharField(blank=True, choices=[('reconnaissance', 'Reconnaissance'), ('vulnerability_identification', 'Vulnerability Identification'), ('exploitation', 'Exploitation'), ('internal_reconnaissance', 'Internal Reconnaissance'), ('user_movement', 'User Movement'), ('privilege_escalation', 'Privilege Escalation'), ('notes', 'Notes')], help_text='Phase where the flag was found', max_length=50),
        ),
    ]
