# Generated by Django 4.2.30 on 2026-05-03 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_exploit_custom_exploit_type_flag_custom_flag_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='custom_os',
        ),
        migrations.AddField(
            model_name='machine',
            name='custom_operating_system',
            field=models.CharField(blank=True, max_length=100, verbose_name='Custom OS'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='command',
            field=models.TextField(blank=True, verbose_name='Command'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='output',
            field=models.TextField(blank=True, verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='phase',
            field=models.CharField(choices=[('reconnaissance', 'Reconnaissance'), ('vulnerability_identification', 'Vulnerability Identification'), ('exploitation', 'Exploitation'), ('internal_reconnaissance', 'Internal Reconnaissance'), ('user_movement', 'User Movement'), ('privilege_escalation', 'Privilege Escalation'), ('notes', 'Notes')], max_length=50, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='affected_port',
            field=models.CharField(blank=True, max_length=50, verbose_name='Affected Port'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='affected_service',
            field=models.CharField(blank=True, max_length=200, verbose_name='Affected Service'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='command_used',
            field=models.TextField(blank=True, verbose_name='Command Used'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='custom_exploit_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Custom Type'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='cve',
            field=models.CharField(blank=True, max_length=50, verbose_name='CVE'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Explanation'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='exploit_type',
            field=models.CharField(choices=[('Manual Technique', 'Manual Technique'), ('Custom Exploit', 'Custom Exploit'), ('GitHub Repository', 'GitHub Repository'), ('Searchsploit', 'Searchsploit'), ('Metasploit Module', 'Metasploit Module'), ('Public PoC', 'Public PoC'), ('Other', 'Other')], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='local_path',
            field=models.CharField(blank=True, max_length=255, verbose_name='Local Path'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='objective',
            field=models.CharField(choices=[('Initial Access', 'Initial Access'), ('Remote Code Execution', 'Remote Code Execution'), ('Credential Disclosure', 'Credential Disclosure'), ('User Pivot', 'User Pivot'), ('Privilege Escalation', 'Privilege Escalation'), ('Proof of Concept', 'Proof of Concept')], max_length=50, verbose_name='Objective'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='output',
            field=models.TextField(blank=True, verbose_name='Output'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='result',
            field=models.TextField(blank=True, verbose_name='Result'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='url',
            field=models.URLField(blank=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='exploit',
            name='vulnerability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exploits', to='reports.vulnerability', verbose_name='Vulnerability'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='censored',
            field=models.BooleanField(default=True, verbose_name='Censor in Report'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='custom_flag_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Custom Type'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='flag_type',
            field=models.CharField(choices=[('user.txt', 'user.txt'), ('root.txt', 'root.txt'), ('local.txt', 'local.txt'), ('proof.txt', 'proof.txt'), ('other', 'other')], max_length=20, verbose_name='Flag Type'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='found_commands',
            field=models.TextField(blank=True, help_text='Commands used to obtain this flag', verbose_name='Command(s) Used'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location / Path'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Additional Notes'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='obtained_as_user',
            field=models.CharField(blank=True, max_length=100, verbose_name='Obtained as User'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='phase',
            field=models.CharField(blank=True, choices=[('reconnaissance', 'Reconnaissance'), ('vulnerability_identification', 'Vulnerability Identification'), ('exploitation', 'Exploitation'), ('internal_reconnaissance', 'Internal Reconnaissance'), ('user_movement', 'User Movement'), ('privilege_escalation', 'Privilege Escalation'), ('notes', 'Notes')], help_text='Phase where the flag was found', max_length=50, verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='flag',
            name='value',
            field=models.CharField(max_length=255, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='author',
            field=models.CharField(blank=True, max_length=100, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client_name',
            field=models.CharField(blank=True, help_text='Company/client name (for Pentest/Bug Bounty reports)', max_length=200, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='custom_platform',
            field=models.CharField(blank=True, max_length=100, verbose_name='Custom Platform'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard'), ('Insane', 'Insane'), ('Unknown', 'Unknown')], default='Unknown', max_length=10, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='operating_system',
            field=models.CharField(choices=[('Linux', 'Linux'), ('Windows', 'Windows'), ('FreeBSD', 'FreeBSD'), ('Other', 'Other'), ('Unknown', 'Unknown')], default='Unknown', max_length=10, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='platform',
            field=models.CharField(choices=[('HackTheBox', 'HackTheBox'), ('TryHackMe', 'TryHackMe'), ('VulnHub', 'VulnHub'), ('DockerLabs', 'DockerLabs'), ('Other', 'Other')], default='Other', max_length=20, verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='report_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='es', max_length=2, verbose_name='Report Language'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='report_type',
            field=models.CharField(choices=[('ctf', 'CTF / HackTheBox / TryHackMe'), ('bug_bounty', 'Bug Bounty Report'), ('pentest', 'Penetration Test (Corporate)')], default='ctf', max_length=20, verbose_name='Report Type'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='scope',
            field=models.TextField(blank=True, help_text='Scope of the engagement (URLs, IP ranges, etc.)', verbose_name='Scope'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='status',
            field=models.CharField(choices=[('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Paused', 'Paused')], default='In Progress', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='target_ip',
            field=models.CharField(blank=True, max_length=255, verbose_name='Target IP'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='affected_port',
            field=models.CharField(blank=True, max_length=50, verbose_name='Affected Port'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='affected_service',
            field=models.CharField(blank=True, max_length=200, verbose_name='Affected Service'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='custom_vulnerability_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Custom Type'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='cve',
            field=models.CharField(blank=True, max_length=50, verbose_name='CVE'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='evidence',
            field=models.TextField(blank=True, verbose_name='Evidence / Proof of Concept'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='how_identified',
            field=models.TextField(blank=True, verbose_name='How was it identified?'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='impact',
            field=models.TextField(blank=True, verbose_name='Technical Impact'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='recommendation',
            field=models.TextField(blank=True, verbose_name='Remediation / Recommendation'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='severity',
            field=models.CharField(choices=[('Info', 'Info'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Info', max_length=20, verbose_name='Severity'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='vulnerability',
            name='vulnerability_type',
            field=models.CharField(choices=[('SQL Injection', 'SQL Injection'), ('XSS', 'XSS'), ('LFI', 'LFI'), ('RFI', 'RFI'), ('SSRF', 'SSRF'), ('Command Injection', 'Command Injection'), ('File Upload', 'File Upload'), ('Path Traversal', 'Path Traversal'), ('Weak Credentials', 'Weak Credentials'), ('Exposed Backup', 'Exposed Backup'), ('Kernel Exploit', 'Kernel Exploit'), ('SUID Misconfiguration', 'SUID Misconfiguration'), ('Sudo Privileges', 'Sudo Privileges'), ('Misconfigured Service', 'Misconfigured Service'), ('Known CVE', 'Known CVE'), ('Other', 'Other')], max_length=50, verbose_name='Type'),
        ),
    ]
